version: '2'
services:
  elasticsearch:
    build: ./docker/elasticsearch
    container_name: elasticsearch
    environment:
      - cluster.name=my-elasticsearch-cluster
      - node.name=first-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - "discovery.zen.ping.unicast.hosts=elasticsearch2"
      - "discovery.zen.minimum_master_nodes=2"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./docker/data/esdata_1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - esnet
  elasticsearch2:
    build: ./docker/elasticsearch
    container_name: elasticsearch2
    environment:
      - cluster.name=my-elasticsearch-cluster
      - node.name=second-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - "discovery.zen.ping.unicast.hosts=elasticsearch"
      - "discovery.zen.minimum_master_nodes=2"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./docker/data/esdata_2:/usr/share/elasticsearch/data
    networks:
      - esnet
  elasticsearch3:
    build: ./docker/elasticsearch
    container_name: elasticsearch3
    environment:
      - cluster.name=my-elasticsearch-cluster
      - node.name=third-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - "discovery.zen.ping.unicast.hosts=elasticsearch"
      - "discovery.zen.minimum_master_nodes=2"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./docker/data/esdata_3:/usr/share/elasticsearch/data
    networks:
      - esnet
  kibana:
    image: docker.elastic.co/kibana/kibana:6.1.2
    container_name: kibana_es
    environment:
      - ELASTICSEARCH_USERNAME=kibana
      - ELASTICSEARCH_PASSWORD=kibana
    ports: ['127.0.0.1:5601:5601']
    depends_on:
      - elasticsearch
    networks:
      - esnet

networks:
  esnet:    